### PR TITLE
add jagged lines to map.

### PR DESCRIPTION
**Pull request by vlandham**

### CODE REVIEW

**Comment by vlandham** [comment]
blast

lets start with extreme and then pull back to fun AND usable.

**Comment by pbeshai** [comment]
Some paths seem to not reach their destination. Wonder if they are fading being removed() due to leaving "visible lines" or if the end points computed from jagged paths aren't working. Just tested turning off jagged paths and it seems that their server pos is in the middle of the ocean. To reproduce, just watch for about 30s.

**Comment by pbeshai** [comment]
I think it looks better if we set a constant radius of `3` or `4` instead of using rScale on the points

**Comment by pbeshai** [comment]
Added encoding download speed in the speed of the path. Could probably use some tuning, but it looks cool

**Comment by pbeshai** [comment]
map

**Comment by pbeshai** [comment]
map

**Comment by vlandham** [comment]
💣 RADICAL ! 👍 🐴

**Pull request merged**
