### PR TITLE
disable zoom by scroll. set sane max zoom.

### PR DESCRIPTION
**Pull request by vlandham**
Add more info under map.

screen shot 2016-10-20 at 12 39 07 pm

### CODE REVIEW

**Comment by vlandham** [comment]
attempt to address #179

**Comment by pbeshai** [comment]
I kind of think these descriptions should go above the map instead of beneath it. What do you think?

**Comment by vlandham** [comment]
thats fine. i was just wanting to get the map as much up the screen as possible.

**Comment by pbeshai** [comment]
yeah let's just try this for now.

**Comment by pbeshai** [comment]
+1

**Pull request merged**
